-- ============================================
-- Social Saver — Seed Data (~100 saves)
-- Run in Supabase SQL Editor AFTER schema.sql
-- ============================================
INSERT INTO saves (
        user_phone,
        url,
        source,
        title,
        category,
        tags,
        summary,
        status,
        action_steps
    )
VALUES -- ═══════════════ FITNESS (15) ═══════════════
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/core-workout-1/',
        'instagram',
        'Core workout routine',
        'Fitness',
        ARRAY ['core','abs','workout','home'],
        'A quick 5-min standing ab circuit—great for daily core strength without equipment.',
        'complete',
        ARRAY ['Do 3 sets of 15 crunches','Hold plank for 60 seconds','Do 20 bicycle crunches']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/resistance-band-2/',
        'instagram',
        'Resistance band workout',
        'Fitness',
        ARRAY ['resistance','bands','strength','home'],
        'Full-body resistance band routine targeting arms, legs, and glutes in 20 minutes.',
        'complete',
        ARRAY ['10 banded squats','15 banded rows','12 lateral walks each side']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=morning-yoga-3',
        'youtube',
        'Morning yoga for energy',
        'Fitness',
        ARRAY ['yoga','morning','flexibility','energy'],
        '15-minute morning yoga flow to wake up the body and boost energy for the day.',
        'complete',
        ARRAY ['Start with sun salutations','Hold warrior 2 for 30s each side','End with savasana']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@fitcoach/hiit-4',
        'tiktok',
        '20-min HIIT fat burner',
        'Fitness',
        ARRAY ['hiit','cardio','fat-burn','intense'],
        'High-intensity interval training: 40s work, 20s rest. Burns 300+ calories.',
        'complete',
        ARRAY ['Burpees x 40s','Mountain climbers x 40s','Jump squats x 40s','Rest 2 min, repeat 4x']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/stretching-5/',
        'instagram',
        'Post-workout stretching guide',
        'Fitness',
        ARRAY ['stretching','recovery','flexibility'],
        'Essential 10-minute cool-down stretches to prevent injury and reduce soreness.',
        'complete',
        ARRAY ['Quad stretch 30s each','Hamstring stretch 30s each','Shoulder cross-body stretch']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=deadlift-form-6',
        'youtube',
        'Perfect deadlift form tutorial',
        'Fitness',
        ARRAY ['deadlift','form','strength','gym'],
        'Step-by-step guide to proper deadlift form. Common mistakes and how to fix them.',
        'complete',
        ARRAY ['Keep back straight','Push through heels','Engage core throughout']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.reddit.com/r/fitness/push-pull-7',
        'other',
        'Push-pull-legs split guide',
        'Fitness',
        ARRAY ['ppl','split','gym','routine'],
        'Complete 6-day push-pull-legs program for intermediate lifters. Includes progression scheme.',
        'complete',
        ARRAY ['Push: bench, OHP, triceps','Pull: rows, pullups, biceps','Legs: squats, RDL, calves']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/mobility-8/',
        'instagram',
        'Hip mobility drills',
        'Fitness',
        ARRAY ['mobility','hips','flexibility','warmup'],
        '5 essential hip mobility exercises to do before any lower body workout.',
        'complete',
        ARRAY ['90/90 stretch','Hip circles','Pigeon pose','Frog stretch']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@gymlife/protein-9',
        'tiktok',
        'How much protein do you really need?',
        'Fitness',
        ARRAY ['protein','nutrition','muscle','diet'],
        'Science-based breakdown: 1.6-2.2g per kg of bodyweight for muscle growth.',
        'complete',
        ARRAY ['Track protein intake for a week','Aim for 30g per meal','Consider whey supplement if needed']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=calisthenics-10',
        'youtube',
        'Beginner calisthenics roadmap',
        'Fitness',
        ARRAY ['calisthenics','bodyweight','beginner','progression'],
        'Progressive calisthenics plan from basic pushups to muscle-ups over 6 months.',
        'complete',
        ARRAY ['Master 20 pushups first','Progress to diamond pushups','Work on pullup negatives']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/jump-rope-11/',
        'instagram',
        'Jump rope cardio workout',
        'Fitness',
        ARRAY ['jumprope','cardio','coordination','fat-burn'],
        '15-min jump rope HIIT workout. Great alternative to running for cardio.',
        'complete',
        ARRAY ['30s basic jumps','30s high knees','30s double unders','Rest 1 min, repeat']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=sleep-recovery-12',
        'youtube',
        'Sleep optimization for athletes',
        'Fitness',
        ARRAY ['sleep','recovery','performance','health'],
        'How to optimize sleep for better muscle recovery: temperature, timing, and supplements.',
        'complete',
        ARRAY ['Keep room at 65-68°F','No screens 1hr before bed','Consider magnesium supplement']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@physio/knee-pain-13',
        'tiktok',
        'Fix knee pain during squats',
        'Fitness',
        ARRAY ['knee','squat','pain','rehab'],
        'Physical therapist explains 3 common causes of knee pain during squats and how to fix each one.',
        'complete',
        ARRAY ['Check ankle mobility','Strengthen VMO with terminal knee extensions','Try box squats first']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/running-plan-14/',
        'instagram',
        'Couch to 5K in 8 weeks',
        'Fitness',
        ARRAY ['running','5k','beginner','cardio'],
        'Progressive running plan for complete beginners. Walk-run intervals building to continuous 5K.',
        'complete',
        ARRAY ['Week 1: 1min run, 2min walk x8','Week 4: 5min run, 1min walk x4','Week 8: continuous 30min run']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=foam-rolling-15',
        'youtube',
        'Foam rolling recovery guide',
        'Fitness',
        ARRAY ['foam-rolling','recovery','myofascial','soreness'],
        'Complete foam rolling routine for post-workout recovery. Target every major muscle group in 15 minutes.',
        'complete',
        ARRAY ['Roll quads 60s each','Roll IT band slowly','Roll upper back on foam roller']
    ),
    -- ═══════════════ FOOD (15) ═══════════════
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/pasta-recipe-16/',
        'instagram',
        'One-pot pasta recipe',
        'Food',
        ARRAY ['pasta','recipe','dinner','easy'],
        'Creamy garlic tuscan chicken pasta—all in one pot, ready in 25 minutes.',
        'complete',
        ARRAY ['Sear chicken in pot','Add garlic, sun-dried tomatoes','Add pasta and broth, simmer 12 min']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@chef/smoothie-17',
        'tiktok',
        'High-protein smoothie bowl',
        'Food',
        ARRAY ['smoothie','protein','breakfast','healthy'],
        'Thick protein smoothie bowl: banana, protein powder, PB, topped with granola and berries.',
        'complete',
        ARRAY ['Blend frozen banana + protein','Pour thick into bowl','Top with granola, berries, honey']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=meal-prep-18',
        'youtube',
        'Sunday meal prep for the week',
        'Food',
        ARRAY ['meal-prep','budget','weekly','healthy'],
        'How to meal prep 5 days of lunches and dinners in 2 hours. Budget-friendly at $50/week.',
        'complete',
        ARRAY ['Cook rice and chicken in bulk','Roast mixed vegetables','Portion into containers']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/air-fryer-19/',
        'instagram',
        'Air fryer crispy tofu',
        'Food',
        ARRAY ['tofu','air-fryer','vegan','crispy'],
        'Perfectly crispy tofu in the air fryer. Press, marinate, air fry at 400°F for 15 min.',
        'complete',
        ARRAY ['Press tofu for 30 min','Marinate in soy sauce, cornstarch','Air fry at 400°F, flip halfway']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@baker/sourdough-20',
        'tiktok',
        'Beginner sourdough bread',
        'Food',
        ARRAY ['sourdough','bread','baking','fermentation'],
        'No-knead sourdough bread recipe for beginners. Only 4 ingredients, incredible results.',
        'complete',
        ARRAY ['Feed starter night before','Mix dough, fold 4x over 4 hrs','Bake in Dutch oven at 450°F']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=ramen-21',
        'youtube',
        'Homemade tonkotsu ramen',
        'Food',
        ARRAY ['ramen','japanese','soup','homemade'],
        'Rich, creamy pork bone broth ramen from scratch. 12-hour broth but worth every minute.',
        'complete',
        ARRAY ['Boil pork bones 12 hrs','Make tare with soy sauce, mirin','Assemble with egg, chashu, nori']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/overnight-oats-22/',
        'instagram',
        'Overnight oats 5 ways',
        'Food',
        ARRAY ['oats','breakfast','meal-prep','healthy'],
        'Five overnight oats variations: PB&J, chocolate, apple pie, tropical, and berry blast.',
        'complete',
        ARRAY ['Mix oats, milk, yogurt, chia','Add toppings per flavor','Refrigerate 6+ hours']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@homecook/steak-23',
        'tiktok',
        'Perfect pan-seared steak',
        'Food',
        ARRAY ['steak','cooking','technique','dinner'],
        'Restaurant-quality steak at home. Reverse sear method for perfect medium-rare every time.',
        'complete',
        ARRAY ['Oven at 275°F until 120°F internal','Rest 10 min','Sear in cast iron with butter, 1 min each side']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=curry-24',
        'youtube',
        'Thai green curry from scratch',
        'Food',
        ARRAY ['curry','thai','spicy','dinner'],
        'Authentic Thai green curry with homemade paste. Way better than store-bought.',
        'complete',
        ARRAY ['Pound green curry paste in mortar','Cook paste in coconut cream','Add chicken, vegetables, simmer 15 min']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/salad-25/',
        'instagram',
        'Mediterranean grain bowl',
        'Food',
        ARRAY ['salad','mediterranean','healthy','lunch'],
        'Hearty grain bowl with farro, roasted chickpeas, feta, cucumber, and lemon-tahini dressing.',
        'complete',
        ARRAY ['Cook farro 25 min','Roast chickpeas with cumin','Assemble with veggies and dressing']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@dessert/cookies-26',
        'tiktok',
        'Brown butter chocolate chip cookies',
        'Food',
        ARRAY ['cookies','baking','dessert','chocolate'],
        'The BEST chocolate chip cookies: browned butter, two types of chocolate, sea salt finish.',
        'complete',
        ARRAY ['Brown the butter until nutty','Chill dough 24-48 hrs','Bake at 375°F for 11 min']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=sushi-27',
        'youtube',
        'Homemade sushi rolls for beginners',
        'Food',
        ARRAY ['sushi','japanese','rice','seafood'],
        'Step-by-step guide to making California rolls at home. Rice seasoning is key.',
        'complete',
        ARRAY ['Season rice with vinegar, sugar, salt','Spread on nori sheet','Roll with bamboo mat, slice']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/tacos-28/',
        'instagram',
        'Street-style carnitas tacos',
        'Food',
        ARRAY ['tacos','mexican','pork','street-food'],
        'Slow-cooker carnitas with quick-pickled onions and fresh cilantro-lime crema.',
        'complete',
        ARRAY ['Slow cook pork shoulder 8 hrs','Broil to crisp edges','Serve on corn tortillas with toppings']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@nutrition/gut-health-29',
        'tiktok',
        'Fermented foods for gut health',
        'Food',
        ARRAY ['gut-health','fermented','probiotics','nutrition'],
        'Top 5 fermented foods to eat daily for better digestion: kimchi, kefir, sauerkraut, miso, yogurt.',
        'complete',
        ARRAY ['Start with 1 serving daily','Rotate between different fermented foods','Pair with prebiotic fiber']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=coffee-30',
        'youtube',
        'Pour-over coffee masterclass',
        'Food',
        ARRAY ['coffee','pour-over','technique','morning'],
        'Perfect pour-over coffee: grind size, water temp (205°F), bloom time, and pour technique.',
        'complete',
        ARRAY ['Use 1:16 coffee to water ratio','Bloom 30 seconds','Pour in slow circles for 3 min total']
    ),
    -- ═══════════════ CODING (15) ═══════════════
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=react-hooks-31',
        'youtube',
        'React hooks deep dive',
        'Coding',
        ARRAY ['react','hooks','javascript','frontend'],
        'Complete guide to React hooks: useState, useEffect, useCallback, useMemo, and custom hooks.',
        'complete',
        ARRAY ['Practice useState with counter app','Build useEffect data fetcher','Create a custom useLocalStorage hook']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=nextjs-32',
        'youtube',
        'Next.js 14 app router tutorial',
        'Coding',
        ARRAY ['nextjs','react','fullstack','routing'],
        'Building a full-stack app with Next.js 14 App Router, Server Components, and Server Actions.',
        'complete',
        ARRAY ['Set up app directory structure','Create server components for data fetching','Add server actions for mutations']
    ),
    (
        'whatsapp:+1234567890',
        'https://dev.to/python-patterns-33',
        'other',
        'Python design patterns explained',
        'Coding',
        ARRAY ['python','design-patterns','architecture','oop'],
        'Top 10 design patterns in Python: Singleton, Factory, Observer, Strategy, Decorator, and more.',
        'complete',
        ARRAY ['Study Singleton for config management','Use Factory for object creation','Apply Observer for event systems']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=docker-34',
        'youtube',
        'Docker for beginners',
        'Coding',
        ARRAY ['docker','devops','containers','deployment'],
        'Docker fundamentals: images, containers, volumes, networking, and docker-compose.',
        'complete',
        ARRAY ['Install Docker Desktop','Write a Dockerfile for your app','Create docker-compose.yml for multi-service']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@coder/git-tips-35',
        'tiktok',
        'Git tricks you should know',
        'Coding',
        ARRAY ['git','version-control','tips','productivity'],
        '10 git commands beyond basic add/commit/push: stash, rebase, cherry-pick, bisect, reflog.',
        'complete',
        ARRAY ['Use git stash for quick context switches','Learn interactive rebase for clean history','Use git bisect to find bugs']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=typescript-36',
        'youtube',
        'TypeScript generics masterclass',
        'Coding',
        ARRAY ['typescript','generics','types','advanced'],
        'Deep dive into TypeScript generics: constraints, conditional types, mapped types, and utility types.',
        'complete',
        ARRAY ['Start with basic generic functions','Learn extends constraints','Build utility types from scratch']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/api-design-37/',
        'instagram',
        'REST API design best practices',
        'Coding',
        ARRAY ['api','rest','backend','design'],
        '12 rules for designing clean, consistent REST APIs: naming, versioning, pagination, error handling.',
        'complete',
        ARRAY ['Use plural nouns for endpoints','Implement cursor-based pagination','Return consistent error objects']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=sql-38',
        'youtube',
        'Advanced SQL queries tutorial',
        'Coding',
        ARRAY ['sql','database','queries','backend'],
        'Window functions, CTEs, recursive queries, and query optimization techniques in PostgreSQL.',
        'complete',
        ARRAY ['Practice ROW_NUMBER and RANK','Write CTEs for complex queries','Use EXPLAIN ANALYZE for optimization']
    ),
    (
        'whatsapp:+1234567890',
        'https://dev.to/css-grid-39',
        'other',
        'CSS Grid layout complete guide',
        'Coding',
        ARRAY ['css','grid','layout','frontend'],
        'Everything about CSS Grid: grid-template, fr units, areas, auto-fit, minmax, and responsive patterns.',
        'complete',
        ARRAY ['Learn grid-template-columns','Use auto-fit with minmax for responsive','Name grid areas for complex layouts']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=system-design-40',
        'youtube',
        'System design interview prep',
        'Coding',
        ARRAY ['system-design','interview','architecture','scalability'],
        'How to approach system design interviews: load balancers, caching, databases, message queues.',
        'complete',
        ARRAY ['Start with requirements gathering','Draw high-level architecture','Discuss trade-offs and bottlenecks']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@devtips/vscode-41',
        'tiktok',
        'VS Code shortcuts that save hours',
        'Coding',
        ARRAY ['vscode','productivity','shortcuts','tools'],
        'Top 15 VS Code keyboard shortcuts and extensions for 10x developer productivity.',
        'complete',
        ARRAY ['Cmd+P for quick file open','Cmd+Shift+L to select all occurrences','Install Copilot and GitLens extensions']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=graphql-42',
        'youtube',
        'GraphQL vs REST: when to use which',
        'Coding',
        ARRAY ['graphql','rest','api','comparison'],
        'Detailed comparison of GraphQL and REST. Use cases, performance, complexity trade-offs.',
        'complete',
        ARRAY ['Use REST for simple CRUD','Choose GraphQL for complex nested data','Consider tRPC for full-stack TypeScript']
    ),
    (
        'whatsapp:+1234567890',
        'https://dev.to/testing-43',
        'other',
        'Testing pyramid: unit, integration, e2e',
        'Coding',
        ARRAY ['testing','jest','cypress','quality'],
        'How to structure your test suite: 70% unit, 20% integration, 10% e2e. Tools and strategies.',
        'complete',
        ARRAY ['Write unit tests with Jest','Integration tests with Supertest','E2E tests with Cypress or Playwright']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=aws-lambda-44',
        'youtube',
        'Serverless with AWS Lambda',
        'Coding',
        ARRAY ['aws','lambda','serverless','cloud'],
        'Building serverless APIs with AWS Lambda, API Gateway, and DynamoDB. Cost-effective and scalable.',
        'complete',
        ARRAY ['Set up SAM CLI','Create Lambda function handler','Configure API Gateway routes']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/regex-45/',
        'instagram',
        'Regex cheat sheet for developers',
        'Coding',
        ARRAY ['regex','reference','programming','patterns'],
        'Visual regex cheat sheet: character classes, quantifiers, groups, lookaheads, and common patterns.',
        'complete',
        ARRAY ['Learn \\d, \\w, \\s basics','Practice with email validation regex','Use regex101.com for testing']
    ),
    -- ═══════════════ DESIGN (12) ═══════════════
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/color-theory-46/',
        'instagram',
        'Color theory for UI designers',
        'Design',
        ARRAY ['color','ui','theory','visual'],
        'Understanding color harmony: complementary, analogous, triadic schemes and when to use each.',
        'complete',
        ARRAY ['Start with 60-30-10 rule','Use coolors.co for palette generation','Test contrast ratios with WebAIM']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=figma-47',
        'youtube',
        'Figma auto-layout masterclass',
        'Design',
        ARRAY ['figma','auto-layout','ui','prototyping'],
        'Advanced Figma auto-layout techniques for responsive designs and component systems.',
        'complete',
        ARRAY ['Set up base frame with auto-layout','Use fill and hug for responsiveness','Create variants with auto-layout']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@uxdesign/typography-48',
        'tiktok',
        'Typography hierarchy in 60 seconds',
        'Design',
        ARRAY ['typography','hierarchy','ui','fonts'],
        'Quick guide to type hierarchy: scale, weight, color, and spacing to create visual rhythm.',
        'complete',
        ARRAY ['Limit to 2 font families','Use modular scale (1.25 ratio)','Ensure 4px baseline grid']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=design-system-49',
        'youtube',
        'Building a design system from scratch',
        'Design',
        ARRAY ['design-system','components','tokens','consistency'],
        'How to build a complete design system: tokens, components, patterns, and documentation.',
        'complete',
        ARRAY ['Define design tokens first','Build atom-level components','Document usage guidelines']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/glassmorphism-50/',
        'instagram',
        'Glassmorphism UI trend explained',
        'Design',
        ARRAY ['glassmorphism','trend','ui','css'],
        'How to create the glassmorphism effect in CSS: backdrop-filter, transparency, and border.',
        'complete',
        ARRAY ['Use backdrop-filter: blur(16px)','Set background with low alpha','Add subtle 1px border with transparency']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=motion-design-51',
        'youtube',
        'Motion design principles for UI',
        'Design',
        ARRAY ['animation','motion','ux','micro-interactions'],
        'Key principles of UI animation: easing, duration, choreography, and meaningful transitions.',
        'complete',
        ARRAY ['Use ease-out for entrances','Keep animations under 300ms','Stagger related elements with 50ms delay']
    ),
    (
        'whatsapp:+1234567890',
        'https://dribbble.com/shots/dark-mode-52',
        'other',
        'Dark mode design principles',
        'Design',
        ARRAY ['dark-mode','ui','accessibility','theme'],
        'Best practices for dark mode: surface elevation, color adaptation, and maintaining readability.',
        'complete',
        ARRAY ['Use dark grays not pure black','Reduce saturation in dark mode','Ensure 4.5:1 contrast ratio minimum']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@designer/icon-design-53',
        'tiktok',
        'Designing consistent icon sets',
        'Design',
        ARRAY ['icons','consistency','vector','visual'],
        'Rules for cohesive icon design: stroke width, corner radius, optical alignment, and sizing.',
        'complete',
        ARRAY ['Use consistent 24px grid','Keep 2px stroke weight','Optically adjust round shapes slightly larger']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=ux-research-54',
        'youtube',
        'UX research methods overview',
        'Design',
        ARRAY ['ux','research','user-testing','methods'],
        'When to use which UX research method: surveys, interviews, usability tests, A/B tests, analytics.',
        'complete',
        ARRAY ['Interviews for discovery phase','Usability tests for validation','A/B tests for optimization']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/landing-page-55/',
        'instagram',
        'High-converting landing page anatomy',
        'Design',
        ARRAY ['landing-page','conversion','copywriting','layout'],
        'The 7 essential sections of a high-converting landing page and the psychology behind each.',
        'complete',
        ARRAY ['Hero with clear value prop','Social proof section','Strong CTA above the fold']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=responsive-56',
        'youtube',
        'Responsive design strategies 2024',
        'Design',
        ARRAY ['responsive','mobile-first','breakpoints','layout'],
        'Modern responsive design: fluid typography, container queries, and intrinsic design patterns.',
        'complete',
        ARRAY ['Use clamp() for fluid typography','Adopt container queries over media queries','Design mobile-first always']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@uiux/spacing-57',
        'tiktok',
        '8px grid spacing system',
        'Design',
        ARRAY ['spacing','grid','consistency','layout'],
        'Why the 8px grid system works: visual rhythm, easier math, and design-dev alignment.',
        'complete',
        ARRAY ['Base unit: 8px','Small spacing: 4px exception only','Use multiples: 8, 16, 24, 32, 48, 64']
    ),
    -- ═══════════════ TRAVEL (10) ═══════════════
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/bali-guide-58/',
        'instagram',
        'Bali travel guide: 7 days itinerary',
        'Travel',
        ARRAY ['bali','indonesia','itinerary','beaches'],
        '7-day Bali itinerary covering Ubud rice terraces, Seminyak beaches, and Uluwatu temples.',
        'complete',
        ARRAY ['Days 1-3: Ubud (culture, rice terraces)','Days 4-5: Seminyak (beaches, nightlife)','Days 6-7: Uluwatu (temples, surfing)']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=japan-budget-59',
        'youtube',
        'Japan on a budget: complete guide',
        'Travel',
        ARRAY ['japan','budget','tips','asia'],
        'How to visit Japan for under $100/day: JR Pass, capsule hotels, konbini meals, free attractions.',
        'complete',
        ARRAY ['Get 7-day JR Pass ($250)','Eat at konbini stores for cheap','Visit free shrines and parks']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@traveler/packing-60',
        'tiktok',
        'Minimalist packing: one bag travel',
        'Travel',
        ARRAY ['packing','minimalist','backpack','tips'],
        'How to pack everything in a 40L backpack for 2 weeks: packing cubes, versatile clothing, and laundry strategy.',
        'complete',
        ARRAY ['Use packing cubes to organize','Pack 5 tops, 2 bottoms, 1 jacket','Do laundry every 4-5 days']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/iceland-61/',
        'instagram',
        'Iceland Ring Road road trip',
        'Travel',
        ARRAY ['iceland','roadtrip','nature','photography'],
        '10-day Ring Road itinerary: waterfalls, glaciers, black sand beaches, and the northern lights.',
        'complete',
        ARRAY ['Rent a 4x4 campervan','Visit Golden Circle first','Chase northern lights in the north']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=flight-deals-62',
        'youtube',
        'How to find cheap flights every time',
        'Travel',
        ARRAY ['flights','budget','hack','booking'],
        'Flight booking strategy: use Google Flights, book 6-8 weeks early, fly midweek, error fare alerts.',
        'complete',
        ARRAY ['Set Google Flights price alerts','Book Tuesday-Thursday flights','Check Scott Cheap Flights for deals']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@nomad/coworking-63',
        'tiktok',
        'Best cities for digital nomads 2024',
        'Travel',
        ARRAY ['digital-nomad','remote-work','cities','lifestyle'],
        'Top 10 cities for remote work: Lisbon, Chiang Mai, Medellin, Bali, Tbilisi, and more.',
        'complete',
        ARRAY ['Lisbon: great cafes and wifi','Chiang Mai: $800/month total cost','Medellin: perfect weather year-round']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/italy-food-64/',
        'instagram',
        'Italian food tour: Rome to Naples',
        'Travel',
        ARRAY ['italy','food-tour','rome','naples'],
        '5-day food-focused Italy trip: Roman pizza, pasta alla gricia, Neapolitan pizza, and limoncello.',
        'complete',
        ARRAY ['Rome: Trastevere for authentic food','Day trip to Naples for pizza','Amalfi Coast for seafood and limoncello']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=travel-safety-65',
        'youtube',
        'Solo travel safety tips',
        'Travel',
        ARRAY ['solo-travel','safety','tips','awareness'],
        'Essential safety tips for solo travelers: share location, money belt, backup documents, local SIM.',
        'complete',
        ARRAY ['Share itinerary with someone','Keep copies of passport in cloud','Get local SIM at airport']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@explore/hidden-gems-66',
        'tiktok',
        'Hidden gems in Southeast Asia',
        'Travel',
        ARRAY ['southeast-asia','hidden-gems','adventure','offbeat'],
        'Off-the-beaten-path destinations: Siargao, Koh Rong, Ninh Binh, Pai, and Siquijor.',
        'complete',
        ARRAY ['Siargao for uncrowded surfing','Koh Rong for pristine beaches','Ninh Binh for stunning karst landscapes']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/travel-photo-67/',
        'instagram',
        'Travel photography tips for phone',
        'Travel',
        ARRAY ['photography','phone','tips','composition'],
        'Take stunning travel photos with just your phone: golden hour, rule of thirds, leading lines.',
        'complete',
        ARRAY ['Shoot during golden hour','Use grid for rule of thirds','Clean lens before every shot']
    ),
    -- ═══════════════ SELF-IMPROVEMENT (15) ═══════════════
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=morning-routine-68',
        'youtube',
        'Morning routine for productivity',
        'Self-Improvement',
        ARRAY ['morning','routine','productivity','habits'],
        'Science-backed morning routine: no phone first 30 min, sunlight exposure, cold water, journal.',
        'complete',
        ARRAY ['Wake up without snooze','Get 10 min sunlight exposure','Journal 3 gratitudes and 3 priorities']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/journaling-69/',
        'instagram',
        'Journaling methods that actually work',
        'Self-Improvement',
        ARRAY ['journaling','reflection','mindfulness','writing'],
        'Compare 5 journaling methods: bullet journal, morning pages, gratitude, prompted, and free-write.',
        'complete',
        ARRAY ['Try gratitude journaling for 1 week','Use prompts when stuck','Write for 10 min minimum']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@mindset/stoicism-70',
        'tiktok',
        'Stoicism for modern life',
        'Self-Improvement',
        ARRAY ['stoicism','philosophy','mindset','resilience'],
        'Core stoic principles: focus on what you control, negative visualization, amor fati, memento mori.',
        'complete',
        ARRAY ['Practice dichotomy of control daily','Do negative visualization once/week','Read Marcus Aurelius Meditations']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=reading-habit-71',
        'youtube',
        'How to read 50 books a year',
        'Self-Improvement',
        ARRAY ['reading','books','habits','learning'],
        'Practical strategies to read more: audiobooks during commute, 25 pages/day rule, book clubs.',
        'complete',
        ARRAY ['Set 25 pages/day minimum','Listen to audiobooks while driving','Quit books you dont enjoy after 50 pages']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/deep-work-72/',
        'instagram',
        'Deep work: eliminate distractions',
        'Self-Improvement',
        ARRAY ['deep-work','focus','productivity','distraction'],
        'Cal Newport deep work summary: time blocking, digital minimalism, and focus rituals.',
        'complete',
        ARRAY ['Schedule 4-hr deep work blocks','Turn off all notifications','Use website blocker during deep work']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=meditation-73',
        'youtube',
        'Meditation for beginners: 10 min/day',
        'Self-Improvement',
        ARRAY ['meditation','mindfulness','stress','beginner'],
        'Start meditating with just 10 minutes a day. Breath focus technique for stress reduction.',
        'complete',
        ARRAY ['Start with 5 min and increase','Focus on breath at nostrils','Use Insight Timer app (free)']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@lifehack/time-mgmt-74',
        'tiktok',
        'Time management: Eisenhower Matrix',
        'Self-Improvement',
        ARRAY ['time-management','eisenhower','prioritization','productivity'],
        'Organize tasks by urgency and importance. Do, schedule, delegate, or eliminate.',
        'complete',
        ARRAY ['Urgent+Important: Do now','Important not urgent: Schedule','Not important: Delegate or delete']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=public-speaking-75',
        'youtube',
        'Public speaking without fear',
        'Self-Improvement',
        ARRAY ['public-speaking','confidence','communication','career'],
        'Overcome public speaking anxiety: structured preparation, practice technique, and audience connection.',
        'complete',
        ARRAY ['Structure: hook, 3 points, close','Practice out loud 5x minimum','Make eye contact with 3 friendly faces']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/networking-76/',
        'instagram',
        'Networking for introverts',
        'Self-Improvement',
        ARRAY ['networking','introverts','career','social'],
        'Practical networking tips for introverts: prepare questions, follow up within 24h, 1-on-1 over groups.',
        'complete',
        ARRAY ['Prepare 3 conversation starters','Follow up with LinkedIn message','Prefer coffee chats over big events']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@finance/budgeting-77',
        'tiktok',
        '50/30/20 budgeting rule explained',
        'Self-Improvement',
        ARRAY ['budgeting','finance','money','saving'],
        'Simple budgeting framework: 50% needs, 30% wants, 20% savings and debt repayment.',
        'complete',
        ARRAY ['Calculate after-tax income','Allocate 50% to essentials','Automate 20% to savings']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=habit-tracking-78',
        'youtube',
        'Atomic Habits: habit stacking guide',
        'Self-Improvement',
        ARRAY ['habits','atomic-habits','behavior','psychology'],
        'James Clear habit stacking: attach new habits to existing ones for automatic consistency.',
        'complete',
        ARRAY ['Identify current habits as anchors','Stack: After coffee, I will journal','Track with a simple habit tracker']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/cold-exposure-79/',
        'instagram',
        'Cold exposure benefits and protocol',
        'Self-Improvement',
        ARRAY ['cold-exposure','health','dopamine','resilience'],
        'Cold shower protocol: start 30 seconds, build to 2 minutes. Increases dopamine 250% for hours.',
        'complete',
        ARRAY ['Start with 30s cold at end of shower','Build to 2 min over 2 weeks','Do it first thing in the morning']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=negotiation-80',
        'youtube',
        'Negotiation tactics from FBI negotiator',
        'Self-Improvement',
        ARRAY ['negotiation','communication','career','psychology'],
        'Chris Voss tactics: mirroring, labeling emotions, calibrated questions, and tactical empathy.',
        'complete',
        ARRAY ['Mirror last 3 words they said','Label: It seems like you feel...','Ask how am I supposed to do that?']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@learn/memory-81',
        'tiktok',
        'Memory palace technique for studying',
        'Self-Improvement',
        ARRAY ['memory','learning','study','technique'],
        'Ancient memory technique: place information in familiar locations in your mind for perfect recall.',
        'complete',
        ARRAY ['Choose a familiar building','Place items in specific rooms','Walk through mentally to recall']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=dopamine-detox-82',
        'youtube',
        'Dopamine detox: reset your brain',
        'Self-Improvement',
        ARRAY ['dopamine','detox','focus','digital-minimalism'],
        'How to do a dopamine detox: eliminate high-stimulation activities for 24h to reset reward circuits.',
        'complete',
        ARRAY ['No phone, social media, or junk food','Do boring activities: walk, journal, clean','Reintroduce stimuli mindfully next day']
    ),
    -- ═══════════════ BUSINESS (13) ═══════════════
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=startup-ideas-83',
        'youtube',
        'How to validate a startup idea',
        'Business',
        ARRAY ['startup','validation','mvp','entrepreneurship'],
        'Idea validation framework: problem interviews, landing page test, pre-sell, then build MVP.',
        'complete',
        ARRAY ['Talk to 20 potential customers','Build a landing page with waitlist','Pre-sell before building']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/personal-brand-84/',
        'instagram',
        'Building a personal brand on LinkedIn',
        'Business',
        ARRAY ['linkedin','personal-brand','career','content'],
        'LinkedIn content strategy: post 3x/week, share stories not just tips, engage in comments.',
        'complete',
        ARRAY ['Define your niche and audience','Post Monday, Wednesday, Friday','Spend 15 min/day commenting on others posts']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@biz/pricing-85',
        'tiktok',
        'Psychology of pricing strategies',
        'Business',
        ARRAY ['pricing','psychology','marketing','strategy'],
        'Pricing psychology: anchoring, charm pricing, decoy effect, and value-based pricing.',
        'complete',
        ARRAY ['Show highest price first (anchoring)','Use $99 instead of $100','Add a decoy option to push preferred tier']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=saas-metrics-86',
        'youtube',
        'SaaS metrics that matter',
        'Business',
        ARRAY ['saas','metrics','analytics','growth'],
        'Key SaaS metrics: MRR, churn rate, LTV, CAC, LTV:CAC ratio, and NPS. Benchmarks included.',
        'complete',
        ARRAY ['Track MRR and growth rate weekly','Keep churn under 5% monthly','Aim for 3:1 LTV:CAC ratio']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/email-marketing-87/',
        'instagram',
        'Email marketing that converts',
        'Business',
        ARRAY ['email','marketing','conversion','copywriting'],
        'High-converting email framework: curiosity subject line, personal story, clear CTA, PS line.',
        'complete',
        ARRAY ['Write subject lines under 40 chars','Lead with story not pitch','Single clear CTA per email']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=freelance-88',
        'youtube',
        'Freelancing: from $0 to $10K/month',
        'Business',
        ARRAY ['freelancing','income','career','side-hustle'],
        'Roadmap to $10K/month freelancing: niche down, portfolio, cold outreach, raise rates.',
        'complete',
        ARRAY ['Pick one specific skill to sell','Build 3 portfolio pieces','Send 10 cold emails per day']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@founder/pitch-deck-89',
        'tiktok',
        'Perfect pitch deck in 10 slides',
        'Business',
        ARRAY ['pitch-deck','fundraising','startup','investors'],
        'The 10 essential pitch deck slides: problem, solution, market, traction, team, ask.',
        'complete',
        ARRAY ['Start with the problem slide','Show traction with real numbers','End with clear funding ask and use of funds']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=seo-basics-90',
        'youtube',
        'SEO fundamentals for beginners',
        'Business',
        ARRAY ['seo','marketing','google','organic'],
        'SEO basics: keyword research, on-page optimization, meta tags, internal linking, and backlinks.',
        'complete',
        ARRAY ['Research keywords with Ubersuggest','Optimize title tags and H1s','Build backlinks through guest posting']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/copywriting-91/',
        'instagram',
        'Copywriting formulas that sell',
        'Business',
        ARRAY ['copywriting','marketing','sales','writing'],
        'Top copywriting formulas: AIDA, PAS, BAB, and the 4 Us. With real examples for each.',
        'complete',
        ARRAY ['AIDA: Attention, Interest, Desire, Action','PAS: Problem, Agitate, Solution','Test headlines with CoSchedule analyzer']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=product-hunt-92',
        'youtube',
        'Launching on Product Hunt successfully',
        'Business',
        ARRAY ['product-hunt','launch','growth','marketing'],
        'Product Hunt launch playbook: timing, hunter selection, community pre-launch, and first hour strategy.',
        'complete',
        ARRAY ['Launch Tuesday-Thursday at midnight PT','Get a top hunter to post','Prepare social media blitz for launch day']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@money/investing-93',
        'tiktok',
        'Index fund investing for beginners',
        'Business',
        ARRAY ['investing','index-funds','retirement','wealth'],
        'Why index funds beat 90% of active managers. DCA into S&P 500 and chill.',
        'complete',
        ARRAY ['Open Vanguard or Fidelity account','Set up automatic monthly investment','Choose total market index fund']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=notion-94',
        'youtube',
        'Notion for business operations',
        'Business',
        ARRAY ['notion','productivity','operations','tools'],
        'Complete Notion setup for small businesses: CRM, project management, SOPs, and team wiki.',
        'complete',
        ARRAY ['Build a CRM database','Create project tracker with Kanban','Write SOPs as templates']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/remote-team-95/',
        'instagram',
        'Managing remote teams effectively',
        'Business',
        ARRAY ['remote-work','management','team','leadership'],
        'Best practices for remote team management: async communication, documentation, and virtual culture.',
        'complete',
        ARRAY ['Default to async communication','Document everything in shared wiki','Schedule optional social time weekly']
    ),
    -- ═══════════════ OTHER (5) ═══════════════
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=houseplants-96',
        'youtube',
        'Indoor houseplant care guide',
        'Other',
        ARRAY ['plants','indoor','care','home'],
        'Beginner-friendly guide to keeping houseplants alive: light, water, soil, and common mistakes.',
        'complete',
        ARRAY ['Check soil moisture before watering','Most plants need indirect light','Repot every 1-2 years']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@diy/desk-setup-97',
        'tiktok',
        'Ultimate desk setup for productivity',
        'Other',
        ARRAY ['desk-setup','productivity','ergonomics','workspace'],
        'Ergonomic desk setup: monitor at eye level, keyboard at elbow height, good chair, cable management.',
        'complete',
        ARRAY ['Monitor arm for height adjustment','Mechanical keyboard at 90° elbow angle','Invest in good chair ($300+ is worth it)']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.instagram.com/p/skincare-98/',
        'instagram',
        'Men skincare routine simplified',
        'Other',
        ARRAY ['skincare','grooming','routine','health'],
        'Simple 3-step skincare: cleanser, moisturizer with SPF, and retinol at night. That is all.',
        'complete',
        ARRAY ['Cleanser morning and night','SPF moisturizer every morning','Retinol 2-3 nights per week']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.youtube.com/watch?v=car-maintenance-99',
        'youtube',
        'Basic car maintenance everyone should know',
        'Other',
        ARRAY ['car','maintenance','diy','essentials'],
        'Essential car maintenance: oil change schedule, tire pressure, brake check, and fluid levels.',
        'complete',
        ARRAY ['Check oil every 5000 miles','Tire pressure monthly','Brake pads every 30-50k miles']
    ),
    (
        'whatsapp:+1234567890',
        'https://www.tiktok.com/@learn/chess-100',
        'tiktok',
        'Learn chess in 15 minutes',
        'Other',
        ARRAY ['chess','strategy','game','learning'],
        'Chess fundamentals: piece movement, basic openings, tactics (forks, pins, skewers), and endgame basics.',
        'complete',
        ARRAY ['Learn piece values and movement','Practice 3 common openings','Study basic checkmate patterns']
    ) ON CONFLICT (user_phone, url_hash) DO NOTHING;